app:
  jwt:
    key: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

server:
  port: 8082

spring:
  data:
    mongodb:
      auto-index-creation: true
      port: 27017
      host: localhost
      database: bioskop_db
      password:
